### ISSUE TITLE
Panic in `nxml_rs::parse` with Unclosed Quote 

### ISSUE THREAD

**Issue by rfuzz** [necauqua/nxml-rs#1]
Hi,

During fuzz testing of the current crate, I encountered an input that causes a panic: if the data being parsed ends with an unclosed `"` character, the `nxml_rs::parse` function panics.

Here’s the test case:

```rust
fn main() {
    if let Ok(_entity) = nxml_rs::parse(r#"""#) {
        println!("OK");
    } else {
        println!("ERR");
    };
}
```

After running it, the following panic occurs:

```shell
thread 'main' panicked at /home/ubuntu/nxml-rs/nxml-rs/src/tokenizer.rs:166:27:
begin <= end (1 <= 0) when slicing `"`
stack backtrace:
   0: rust_begin_unwind
             at /rustc/ed04567ba1d5956d1080fb8121caa005ce059e12/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/ed04567ba1d5956d1080fb8121caa005ce059e12/library/core/src/panicking.rs:74:14
   2: core::str::slice_error_fail_rt
   3: core::str::slice_error_fail
             at /rustc/ed04567ba1d5956d1080fb8121caa005ce059e12/library/core/src/str/mod.rs:68:5
   4: core::str::traits::<impl core::slice::index::SliceIndex<str> for core::ops::range::Range<usize>>::index
             at /rustc/ed04567ba1d5956d1080fb8121caa005ce059e12/library/core/src/str/traits.rs:240:21
   5: core::str::traits::<impl core::ops::index::Index<I> for str>::index
             at /rustc/ed04567ba1d5956d1080fb8121caa005ce059e12/library/core/src/str/traits.rs:60:9
   6: nxml_rs::tokenizer::Tokenizer::next_token
             at /home/ubuntu/nxml-rs/nxml-rs/src/tokenizer.rs:166:27
   7: nxml_rs::parser::Parser::parse_inner
             at /home/ubuntu/nxml-rs/nxml-rs/src/parser.rs:83:43
   8: nxml_rs::parser::Parser::parse
             at /home/ubuntu/nxml-rs/nxml-rs/src/parser.rs:79:9
   9: nxml_rs::parser::parse
             at /home/ubuntu/nxml-rs/nxml-rs/src/parser.rs:36:5
  10: nxml_rs_fuzz_target_test::main
             at ./src/main.rs:2:26
  11: core::ops::function::FnOnce::call_once
             at /rustc/ed04567ba1d5956d1080fb8121caa005ce059e12/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Version: `commit 598882df1146d135646303aeae9947e9600d080a`

**Comment by necauqua** [comment]
good bot

---
Huh, given that it's mostly just a rewrite of the C code, I wonder if this panic is a buffer overrun in the original :smile:
OTOH the rewrite is not a 1-to-1 translation so it very well might've been my derp
